package exception

import (
	"testing"
)

func Test_test(t *testing.T) {
	test()
}

func Test_test1(t *testing.T) {
		test1() //error
}
