package exception

import (
	"testing"
)

func Test_test(t *testing.T) {
	test()
}
